dist: trusty
language: java
sudo: false
install: true
jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk11

addons:
  apt:
    packages:
      - oracle-java8-installer
      - openjdk-8-jdk

notifications:
  webhooks:
    urls:
      - secure: "MYOOaLxyB6z52zhJzjt82+m30Ou9642z87gdWk+dDtCCDdtDbK/IZSjK2WW8K6Z1/Xy5x9QfJq9bvCA0mvLWs9SpcPHbGtmC3e08LI1JHTz1yVSm5oAogWzvu10zhuODy4T9CVDH5lfHPUAvf/R6pyPGgGMbpJ/Bt3o5nM/V5IoFyyFGZ0OnICSXWjuxOKhRC/GW8kklJFfuFbgSLWu/JRt6AFtZZo/xf1FNaSdwEtqzooMHET3JWhbXFj97tFW9ni4b4knetSB3QaRBG6tSRZUUJM+u6AEPr0Svz481pgmARO57PP/YQC4zVze4FbxeXGlp7ja/9W8PlP6fw0vDIKUBaaxJf70eLOKcVBepUC86x7gZL9eUNMiaiR1T/awQWb38VOGGmlZEZ/BiM8buX0EhXhE0dRe8cbUoMOj8LlfHE31aVmY/SZRKpgYa62DRo/WR/PdvoXZGPqhG6y1srejQf6yYeD0zUC+qW2lWh08KVbEQXBmb3NmYdC4k/LHXEjsC+Lu7Upl7z2PuQsZTu7ekqMp0qnkI3Z1+Vigr/9zdWEXnyDejFsqE3tWQk0wVbrOzY1AKTtrkSSr5jiNpt0M2DOKpdaZgJKz8LMgjExTXu9MRUSg8yFeDv5jXuc6BZYVZ+6s3+J64vyok1Pp6j8n9xv4BXlxmEHaYsl2pawE="

before_install: "echo \"MAVEN_OPTS='-Xms1g -Xmx2g'\" > ~/.mavenrc"

script: mvn clean install
cache:
  directories:
    - '$HOME/.m2/repository'


